void print_opcode(int a)
{
	switch(a)
	{
	case 0x00: printf("nop\n");
		   break;
	case 0x01: printf("aconst_null\n");
		   break;
	case 0x02: printf("iconst_m1\n");
	     	   break;
	case 0x03: printf("iconst_0\n");
		   break;
	case 0x04: printf("iconst_1\n");
	           break;
	case 0x05: printf("iconst_2\n");
	           break;
	case 0x06: printf("iconst_3\n");
	           break;
	case 0x07: printf("iconst_4\n");
	           break;
	case 0x08: printf("iconst_5\n");
	   	   break;
	case 0x09: printf("iconst_0\n");
		   break;
	case 0x0a: printf("iconst_1\n");
		   break;
	case 0x0b: printf("fconst_0\n");
		   break;
	case 0x0c: printf("fconst_1\n");
		   break;
	case 0x0d: printf("fconst_2\n");
		   break;
	case 0x0e: printf("dconst_0\n");
		   break;
	case 0x0f: printf("dconst_1\n");
		   break;
	case 0x10: printf("bipush\n");
		   break;
	case 0x11: printf("sipush\n");
		   break;
	case 0x12: printf("ldc\n");
		   break;
	case 0x13: printf("ldc_w\n");
		   break;
	case 0x14: printf("ldc2_w\n");
		   break;
	case 0x15: printf("iload\n");
		   break;
	case 0x16: printf("dload\n");
		   break;
	case 0x17: printf("fload\n");
		   break;
	case 0x18: printf("dload\n");
		   break;
	case 0x19: printf("aload\n");
	           break;
	case 0x1a: printf("iload_0\n");
		   break;
	case 0x1b: printf("iload_1\n");
		   break;
	case 0x1c: printf("iload_2\n");
		   break;
	case 0x1d: printf("iload_3\n");
	 	   break;
	case 0x1e: printf("lload_0\n");
		   break;
	case 0x1f: printf("lload_1\n");
		   break;
	case 0x20: printf("lload_2\n");
		   break;
	case 0x21: printf("lload_3\n");
		   break;
	case 0x22: printf("fload_0\n");
		   break;
	case 0x23: printf("fload_1\n");
		   break;
	case 0x24: printf("fload_2\n");
		   break;
	case 0x25: printf("fload_3\n");
		   break;
	case 0x26: printf("dload_0\n");
		   break;
	case 0x27: printf("dload_1\n");
		   break;
	case 0x28: printf("dload_2\n");
		   break;
	case 0x29: printf("dload_3\n");
		   break;
	case 0x2a: printf("aload_0\n");
		   break;
	case 0x2b: printf("aload_1\n");
		   break;
	case 0x2c: printf("aload_2\n");
		   break;
	case 0x2d: printf("aload_3\n");
		   break;
	case 0x2e: printf("iaload\n");
		   break;
	case 0x2f: printf("laload\n");
		   break;
	case 0x30: printf("faload\n");
		   break;
	case 0x31: printf("daload\n");
		   break;
	case 0x32: printf("aaload\n");
		   break;
	case 0x33: printf("baload\n");
		   break;
	case 0x34: printf("caload\n");
		   break;
	case 0x35: printf("saload\n");
		   break;
	case 0x36: printf("istore\n");
	           break;
	case 0x37: printf("lstore\n");
	           break;
	case 0x38: printf("fstore\n");
		   break;
	case 0x39: printf("dstore\n");
		   break;
	case 0x3a: printf("astore\n");
		   break;
	case 0x3b: printf("istore_0\n");
		   break;
	case 0x3c: printf("istore_1\n");
		   break;
	case 0x3d: printf("istore_2\n");
		   break;
	case 0x3e: printf("istore_3\n");
		   break;
	case 0x3f: printf("istore_0\n");
		   break;
	case 0x40: printf("lstore_1\n");
		   break;
	case 0x41: printf("lstore_2\n");
		   break;
	case 0x42: printf("lstore_3\n");
		   break;
	case 0x43: printf("fstore_0\n");
		   break;
	case 0x44: printf("fstore_1\n");
		   break;
	case 0x45: printf("fstore_2\n");
		   break;
	case 0x46: printf("fstore_3\n");
		   break;
	case 0x47: printf("dstore_0\n");
		   break;
	case 0x48: printf("dstore_1\n");
		   break;
	case 0x49: printf("dstore_2\n");
		   break;
	case 0x4a: printf("dstore_3\n");
		   break;
	case 0x4b: printf("astore_0\n");
		   break;
	case 0x4c: printf("astore_1\n");
		   break;
	case 0x4d: printf("astore_2\n");
		   break;
	case 0x4e: printf("astore_3\n");
		   break;
	case 0x4f: printf("iastore\n");
		   break;
	case 0x50: printf("lastore\n");
		   break;
	case 0x51: printf("fastore\n");
		   break;
	case 0x52: printf("dastore\n");
		   break;
	case 0x53: printf("aastore\n");
		   break;
	case 0x54: printf("bastore\n");
	           break;
	case 0x55: printf("castore\n");
	           break;
	case 0x56: printf("sastore\n");
		   break;
	case 0x57: printf("pop\n");
		   break;
	case 0x58: printf("pop2\n");
		   break;
	case 0x59: printf("dup\n");
		   break;
	case 0x5a: printf("dup_x1\n");
		   break;
	case 0x5b: printf("dup_x2\n");
		   break;
	case 0x5c: printf("dup2\n");
		   break;
	case 0x5d: printf("dup2_x1\n");
		   break;
	case 0x5e: printf("dup2_x2\n");
		   break;
	case 0x5f: printf("swap\n");
		   break;
	case 0x60: printf("iadd\n");
		   break;
	case 0x61: printf("ladd\n");
		   break;
	case 0x62: printf("fadd\n");
		   break;
	case 0x63: printf("dadd\n");
		   break;
	case 0x64: printf("isub\n");
		   break;
	case 0x65: printf("lsub\n");
		   break;
	case 0x66: printf("fsub\n");
		   break;
	case 0x67: printf("dsub\n");
		   break;
	case 0x68: printf("imul\n");
		   break;
	case 0x69: printf("lmul\n");
		   break;
	case 0x6a: printf("fmul\n");
		   break;
	case 0x6b: printf("dmul\n");
		   break;
	case 0x6c: printf("idiv\n");
		   break;
	case 0x6d: printf("ldiv\n");
		   break;
	case 0x6e: printf("fdiv\n");
		   break;
	case 0x6f: printf("ddiv\n");
		   break;
	case 0x70: printf("irem\n");
		   break;
	case 0x71: printf("lrem\n");
		   break;
	case 0x72: printf("frem\n");
		   break;
	case 0x73: printf("drem\n");
		   break;
	case 0x74: printf("ineg\n");
		   break;
	case 0x75: printf("lneg\n");
		   break;
	case 0x76: printf("fneg\n");
		   break;
	case 0x77: printf("dneg\n");
		   break;
	case 0x78: printf("ishl\n");
		   break;
	case 0x79: printf("lshl\n");
		   break;
	case 0x7a: printf("ishr\n");
		   break;
	case 0x7b: printf("lshr\n");
		   break;
	case 0x7c: printf("iushr\n");
		   break;
	case 0x7d: printf("lushr\n");
		   break;
	case 0x7e: printf("iand\n");
		   break;
	case 0x7f: printf("land\n");
		   break;
	case 0x80: printf("ior\n");
		   break;
	case 0x81: printf("lor\n");
		   break;
	case 0x82: printf("ixor\n");
		   break;
	case 0x83: printf("lxor\n");
		   break;
	case 0x84: printf("iinc\n");
		   break;
	case 0x85: printf("i2l\n");
		   break;
	case 0x86: printf("i2f\n");
		   break;
	case 0x87: printf("i2d\n");
		   break;
	case 0x88: printf("l2i\n");
		   break;
	case 0x89: printf("l2f\n");
		   break;
	case 0x8a: printf("l2d\n");
		   break;
	case 0x8b: printf("f2i\n");
		   break;
	case 0x8c: printf("f2l\n");
	           break;
	case 0x8d: printf("f2d\n");
		   break;
	case 0x8e: printf("d2i\n");
	           break;
	case 0x8f: printf("d2l\n");
	           break;
	case 0x90: printf("d2f\n");
	           break;
	case 0x91: printf("i2b\n");
	           break;
	case 0x92: printf("i2c\n");
	           break;
	case 0x93: printf("i2s\n");
	           break;
	case 0x94: printf("icmp\n");
	           break;
	case 0x95: printf("fcmpl\n");
	           break;
	case 0x96: printf("fcmpg\n");
	           break;
	case 0x97: printf("dcmpl\n");
	           break;
	case 0x98: printf("dcmpg\n");
	           break;
	case 0x99: printf("ifeq\n");
	           break;
	case 0x9a: printf("ifne\n");
	           break;
	case 0x9b: printf("iflt\n");
	           break;
	case 0x9c: printf("ifge\n");
	           break;
	case 0x9d: printf("ifgt\n");
	           break;
	case 0x9e: printf("ifle\n");
	           break;
	case 0x9f: printf("if_icmpeq\n");
	           break;
	case 0xa0: printf("if_icmpne\n");
	           break;
	case 0xa1: printf("if_icmplt\n");
	           break;
	case 0xa2: printf("if_icmpge\n");
	           break;
	case 0xa3: printf("if_icmpgt\n");
	           break;
	case 0xa4: printf("if_icmple\n");
	           break;
	case 0xa5: printf("if_acmpeq\n");
	           break;
	case 0xa6: printf("if_acmpne\n");
	           break;
	case 0xa7: printf("goto\n");
	           break;
	case 0xa8: printf("jsr\n");
	           break;
	case 0xa9: printf("ret\n");
	           break;
	case 0xaa: printf("tableswitch\n");
	           break;
	case 0xab: printf("lookupswitch\n");
	           break;
	case 0xac: printf("ireturn\n");
	           break;
	case 0xad: printf("lreturn\n");
	           break;
	case 0xae: printf("freturn\n");
	           break;
	case 0xaf: printf("dreturn\n");
	           break;
	case 0xb0: printf("areturn\n");
	           break;
	case 0xb1: printf("return\n");
	           break;
	case 0xb2: printf("getstatic\n");
	           break;
	case 0xb3: printf("putstatic\n");
	           break;
	case 0xb4: printf("getfield\n");
	           break;
	case 0xb5: printf("putfield\n");
	           break;
	case 0xb6: printf("invokevirtual\n");
	           break;
	case 0xb7: printf("invokespecial\n");
	           break;
	case 0xb8: printf("invokestatic\n");
	           break;
	case 0xb9: printf("invokeinterface\n");
	           break;
	case 0xba: printf("xxxunusedxxx\n");
	           break;
	case 0xbb: printf("new\n");
	           break;
	case 0xbc: printf("newarray\n");
	           break;
	case 0xbd: printf("ianewarray\n");
	           break;
	case 0xbe: printf("arraylength\n");
	           break;
	case 0xbf: printf("athrow\n");
	           break;
	case 0xc0: printf("checkcast\n");
	           break;
	case 0xc1: printf("instanceof\n");
	           break;
	case 0xc2: printf("monitorenter\n");
	           break;
	case 0xc3: printf("monitorexit\n");
	           break;
	case 0xc4: printf("wide\n");
	           break;
	case 0xc5: printf("multianewarray\n");
	           break;
	case 0xc6: printf("ifnull\n");
	           break;
	case 0xc7: printf("ifnonnull\n");
	           break;
	case 0xc8: printf("goto_w\n");
	           break;
	case 0xc9: printf("jsr_w\n");
	           break;
//quick opcodes:
	case 0xcb: printf("ldc_quick\n");
	           break;
	case 0xcc: printf("ldc_w_quick\n");
	           break;
	case 0xcd: printf("ldc2_w_quick\n");
	           break;
	case 0xce: printf("getfield_quick\n");
	           break;
	case 0xcf: printf("putfield_quick\n");
	           break;
	case 0xd0: printf("getfield2_quick\n");
	           break;
	case 0xd1: printf("putfield2_quick\n");
	           break;	
	case 0xd2: printf("getstatic_quick\n");
	           break;	
	case 0xd3: printf("putstatic_quick\n");
	           break;	
	case 0xd4: printf("getstatic2_quick\n");
	           break;	
	case 0xd5: printf("putstatic2_quick\n");
	           break;	
	case 0xd6: printf("invokevirtual_quick\n");
	           break;
	case 0xd7: printf("invokenonvirtual_quick\n");
	           break;
	case 0xd8: printf("invokesuper_quick\n");
	           break;	
	case 0xd9: printf("invokestatic_quick\n");
	           break;	
	case 0xda: printf("invokeinterface_quick\n");
	           break;
	case 0xdb: printf("invokevirtualobject_quick\n");
	           break;
	case 0xdd: printf("new_quick\n");
	           break;	
	case 0xde: printf("anewarray_quick\n");
	           break;	
	case 0xdf: printf("multianewarray_quick\n");
	           break;
	case 0xe0: printf("checkcast_quick\n");
	           break;
	case 0xe1: printf("instanceof_quick\n");
	           break;	
	case 0xe2: printf("invokevirtual_quick_w\n");
	           break;
	case 0xe3: printf("getfield_quick_w\n");
	           break;	
	case 0xe4: printf("putfield_quick_w\n");
	           break;	
//reserved opcodes:
	case 0xca: printf("breakpoint\n");
	           break;	
	case 0xfe: printf("impdep1\n");
	           break;	
	case 0xff: printf("impdep2\n");
	           break;	
	}
}
		
	
	

































	

